const menuButton=document.querySelector('.menu-toggle');
const navigation=document.querySelector('.primary-nav');
menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));menuButton.setAttribute('aria-label',open?'Open navigation':'Close navigation');navigation.classList.toggle('is-open',!open)});
navigation.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{menuButton.setAttribute('aria-expanded','false');menuButton.setAttribute('aria-label','Open navigation');navigation.classList.remove('is-open')}));
document.querySelector('#contact-form').addEventListener('submit',event=>{event.preventDefault();const form=new FormData(event.currentTarget);const subject=encodeURIComponent(`Website enquiry: ${form.get('treatment')}`);const body=encodeURIComponent(`Name: ${form.get('name')}\nEmail: ${form.get('email')}\nTreatment: ${form.get('treatment')}\n\n${form.get('message')}`);window.location.href=`mailto:concierge@benicebeauty.com?subject=${subject}&body=${body}`});
const loader=document.querySelector('#page-loader');window.setTimeout(()=>loader.classList.add('is-done'),750);
const revealItems=document.querySelectorAll('.intro,.section-heading,.service-card,.experience-image,.experience-copy,.quote-section blockquote,.booking,.contact-details,.contact-form');revealItems.forEach((item,index)=>{item.classList.add('scroll-reveal');if(item.classList.contains('service-card'))item.style.setProperty('--reveal-delay',`${(index%4)*90}ms`)});
if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -35px 0px'});revealItems.forEach(item=>observer.observe(item))}else revealItems.forEach(item=>item.classList.add('is-visible'));

const siteHeader=document.querySelector('.site-header');const updateHeaderOnScroll=()=>siteHeader.classList.toggle('is-scrolled',window.scrollY>30);window.addEventListener('scroll',updateHeaderOnScroll,{passive:true});updateHeaderOnScroll();

const reviewSlides=[...document.querySelectorAll('.review-slide')];const reviewButtons=[...document.querySelectorAll('.quote-dots button')];if(reviewSlides.length&&reviewButtons.length){let currentReview=0;let reviewTimer;const showReview=index=>{currentReview=index;reviewSlides.forEach((slide,i)=>{slide.hidden=i!==index;slide.classList.toggle('is-active',i===index)});reviewButtons.forEach((button,i)=>{button.classList.toggle('active',i===index);button.setAttribute('aria-pressed',String(i===index))})};const nextReview=()=>showReview((currentReview+1)%reviewSlides.length);const stopReviewRotation=()=>window.clearInterval(reviewTimer);const startReviewRotation=()=>{stopReviewRotation();if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches)reviewTimer=window.setInterval(nextReview,4000)};reviewButtons.forEach((button,index)=>button.addEventListener('click',()=>{showReview(index);startReviewRotation()}));const reviewSection=document.querySelector('.quote-section');reviewSection.addEventListener('mouseenter',stopReviewRotation);reviewSection.addEventListener('mouseleave',startReviewRotation);reviewSection.addEventListener('focusin',stopReviewRotation);reviewSection.addEventListener('focusout',event=>{if(!reviewSection.contains(event.relatedTarget))startReviewRotation()});startReviewRotation()}
